# Práctica 1 - Self-Organising Maps
## Preparación de entorno
#### Importar librerías de código

In [2]:
%reset
# from __future__ import division

import numpy as np
from matplotlib import pyplot as plt
from matplotlib import patches as patches

%matplotlib inline

Nothing done.


#### Dataset que se va a utilizar para el entrenamiento

In [3]:
# Código para obtener el Dataset que se va a usar en el entrenamiento
valor_min = 0
valor_max = 256     #256 porque el valor máximo es exclusivo, es decir, irá de 0 a 255
valores_color = 3
num_colores = 100
datos = np.random.randint(valor_min, valor_max, (num_colores, valores_color))
print(f"La matriz de 100 colores:\n",datos)







La matriz de 100 colores:
 [[ 27 157 180]
 [ 29 158 144]
 [115 191  20]
 [ 79 151 169]
 [ 79 129 122]
 [225 243 172]
 [ 24 227 104]
 [168 131  81]
 [117 165 106]
 [ 64 253 156]
 [  9 133 201]
 [131  76 121]
 [137  93 194]
 [ 71  19 140]
 [159 209  82]
 [200 211  39]
 [162 133 202]
 [201 170 142]
 [203  77  22]
 [116 249 176]
 [122  63  87]
 [ 41 130  49]
 [197 157 238]
 [244 179 170]
 [160 166 139]
 [ 79 118  50]
 [ 85  79 224]
 [121 185  47]
 [141 253 183]
 [175 152 157]
 [139 227 191]
 [242  61 125]
 [ 83 109  56]
 [135 189 192]
 [243  80 245]
 [ 57  14 248]
 [207  10 127]
 [168 241 158]
 [228  69 106]
 [169  43 213]
 [124 167  27]
 [ 53 223  98]
 [128 146 119]
 [213  62 173]
 [235   4 130]
 [182  75 149]
 [161  43   2]
 [158   8  21]
 [207  32 230]
 [226 135 149]
 [ 71 162 188]
 [ 92  23 235]
 [209 199 165]
 [116 121 243]
 [ 39  12 135]
 [225 117 249]
 [ 99 110   8]
 [ 33  34 246]
 [ 49  53  99]
 [247 142 245]
 [219  10  33]
 [187  68   9]
 [ 22  84 218]
 [230 195 192]
 [ 39 216  68

## SOM Setup
#### Variables definidas por el alumno

In [4]:
# Inicializa tamaño del mapa de Kohonen, número de iteraciones y learning rate
# Inicializa normalizar_datos dependiendo de si tienes que normalizar los datos o no
lado_mapa = 10
periodo = 1000
learning_rate = 0.1
normalizar_datos = True

#### A partir de este punto solo hay cálculos. No se introducen más valores "a mano"

In [9]:
# Establece el numero de entradas del mapa y el número de datos que se van a usar para entrenar. 
# Utiliza una función que obtenga automáticamente los valores a partir del Dataset.

def obtener_Entrada(datos):
   valor_aleatorio = np.random.randint(0,256)
   return datos[valor_aleatorio]

# Calcula el vecindario inicial. Debe ser la mitad del lado del mapa de Kohonen
vecindario = lado_mapa/2

# Normaliza los datos si fuese necesario dividiendo cada dato por el máximo en la matriz
# Calculamos el valor maximo de la matriz

valor_maximo = 0
for dato in datos:
    for valor in dato:
        if(valor_maximo < valor):
            valor_maximo = valor  
      
if normalizar_datos:
    datos = datos/valor_max    
    
    
# Crea una matriz de pesos con valores random entre 0 y 1. Usa la función random.random de la librería NumPy
#matriz_pesos = np.random.random((dimensiones de la matriz de pesos))

matriz_pesos = np.random.random((100,3))
print(matriz_pesos)

[[0.52697487 0.18748737 0.37845773]
 [0.80428439 0.50563414 0.79775313]
 [0.51183255 0.51920367 0.3052875 ]
 [0.65457535 0.90511297 0.83711218]
 [0.45006104 0.40169959 0.09096412]
 [0.53006059 0.59137522 0.71617143]
 [0.85067852 0.64260604 0.17067407]
 [0.56349811 0.56783994 0.01054729]
 [0.96407516 0.3377648  0.12468553]
 [0.03106471 0.6944854  0.32440948]
 [0.01918853 0.03211793 0.8911761 ]
 [0.06779807 0.8341059  0.82141244]
 [0.15231194 0.1673051  0.90396959]
 [0.31702736 0.33290495 0.60618813]
 [0.5498076  0.27505812 0.34248651]
 [0.4679716  0.06940978 0.06065595]
 [0.51025139 0.03777014 0.14731754]
 [0.4642015  0.19041006 0.48713998]
 [0.03457102 0.6280124  0.56542753]
 [0.35686145 0.33901425 0.36487799]
 [0.50622838 0.27175404 0.40638478]
 [0.9300082  0.35277563 0.09586698]
 [0.18980971 0.36338972 0.70360242]
 [0.95380534 0.68217105 0.64887095]
 [0.43601073 0.74624456 0.57578346]
 [0.48019443 0.63757977 0.19941752]
 [0.04711027 0.14970521 0.98688373]
 [0.19772348 0.54659777 0.21

#### Funciones para entrenar/clasificar

In [ ]:
# Función para encontrar la BMU
"""
   Encuentra la BMU para un patrón de entrada.
   Entradas: (patrón_de_entrada, matriz_de_pesos, número_de_entradas)
   Salidas:  (bmu, bmu_idx) tupla donde
               bmu: vector de pesos de la neurona ganadora
               bum_idx: coordenadas de la neurona ganadora
"""
patron_entrada = obtener_Entrada(datos)
def calcular_bmu(patron_entrada, m_pesos, m):

SyntaxError: incomplete input (3651684424.py, line 9)

In [ ]:
# Función para calcular el descenso del coeficiente de aprendizaje (eta)
"""
   Calcula el Learning Rate (eta) que corresponde a la i-ésima presentación.
   Entradas: (learning_rate_inicial, iteracion, período)
   Salidas:  learning_rate para la iteración i

"""
def variacion_learning_rate(lr_inicial, i, n_iteraciones):

In [ ]:
# Función para calcular el descenso del vecindario (v)
"""
   Calcula el vecindario  (v) que corresponde a la i-ésima presentación.
   Entradas: (vecindario_inicial, iteracion, período)
   Salidas:  lvecindario para la iteración i

"""
def variacion_vecindario(vecindario_inicial, i, n_iteraciones):

In [ ]:
# Función para calcular el descenso del coeficiente de aprendizaje (eta) en función de la distancia a la BMU
"""
   Calcula la amortiguación de eta en función de la distancia en el mapa entre una neurona y la BMU.
   Entradas: (distancia_BMU, vecindario_actual)
   Salidas:  amortiguación para la iteración

"""
def decay(distancia_BMU, vecindario_actual):
    return np.exp(-distancia_BMU / (2* (vecindario_actual**2)))

#### Funciones para dibujar la salida de la red

In [ ]:
# Función para pintar una matriz de valores como colores RGB
def pintar_mapa(matriz_valores):
    fig = plt.figure()
    
    # Establece ejes
    ax = fig.add_subplot(111, aspect='equal')
    ax.set_xlim((0, matriz_pesos.shape[0]+1))
    ax.set_ylim((0, matriz_pesos.shape[1]+1))
    ax.set_title('Self-Organising Map después de %d iteraciones' % periodo)

    # Dibuja los rectángulos de color RGB
    for x in range(1, matriz_valores.shape[0] + 1):
        for y in range(1, matriz_valores.shape[1] + 1):
            ax.add_patch(patches.Rectangle((x-0.5, y-0.5), 1, 1,
                         facecolor=matriz_valores[x-1,y-1,:],
                         edgecolor='none'))
    plt.show()

## SOM Entrenamiento

In [ ]:
# Entrena la red con el dataset de entrenamiento



## SOM Clasificación

In [ ]:
# Clasifica los patrones de entrenamiento con la matriz de pesos recién entrenada



## SOM Prueba

In [ ]:
# Clasifica nuevos patrones

