# Práctica 1 - Self-Organising Maps
## Preparación de entorno
#### Importar librerías de código

In [26]:
%reset
# from __future__ import division

import numpy as np
from matplotlib import pyplot as plt
from matplotlib import patches as patches

%matplotlib inline

Nothing done.


#### Dataset que se va a utilizar para el entrenamiento

In [27]:
# Código para obtener el Dataset que se va a usar en el entrenamiento
valor_min = 0
valor_max = 256     #256 porque el valor máximo es exclusivo, es decir, irá de 0 a 255
valores_color = 3
num_colores = 100
datos = np.random.randint(valor_min, valor_max, (num_colores, valores_color))
print(f"La matriz de 100 colores:\n",datos)







La matriz de 100 colores:
 [[ 94  66 121]
 [242  52   5]
 [225 232 189]
 [ 55 109 170]
 [245  94  14]
 [199  35 113]
 [ 96  33  91]
 [ 40 134 133]
 [ 78  11  24]
 [166 230  35]
 [202   4  50]
 [128  28 221]
 [ 79 102 150]
 [237 253 126]
 [ 98 202 196]
 [ 99  59  80]
 [234  79 104]
 [ 60 170  13]
 [ 92  92 149]
 [110 185 136]
 [239 196   2]
 [132 112 174]
 [ 60 145  53]
 [ 22 132 178]
 [211 165  22]
 [ 28 242 132]
 [238 245 201]
 [162  33 212]
 [248 160  21]
 [ 13  72 248]
 [ 75 135  17]
 [166 109 191]
 [132  10 244]
 [127 189  90]
 [  8  50  97]
 [107 235 205]
 [225  97  83]
 [ 22  57 104]
 [240  51  77]
 [135 184 194]
 [163 129  49]
 [ 54 168 239]
 [128 126  87]
 [244 122 102]
 [221  74 241]
 [178   4 185]
 [ 78 133 127]
 [209 113 254]
 [156 174 184]
 [196 200 130]
 [247 207 176]
 [ 98 228  35]
 [221 171 108]
 [ 34 112  31]
 [ 50  10 104]
 [110 142 236]
 [ 61  80  99]
 [162 179 106]
 [180 246  69]
 [180 192  50]
 [  1 159 166]
 [164 245  25]
 [223  14 254]
 [166 209 176]
 [157 156 105

## SOM Setup
#### Variables definidas por el alumno

In [28]:
# Inicializa tamaño del mapa de Kohonen, número de iteraciones y learning rate
# Inicializa normalizar_datos dependiendo de si tienes que normalizar los datos o no
lado_mapa = 10
periodo = 1000
learning_rate = 0.1
normalizar_datos = True

#### A partir de este punto solo hay cálculos. No se introducen más valores "a mano"

In [33]:
# Establece el numero de entradas del mapa y el número de datos que se van a usar para entrenar. 
# Utiliza una función que obtenga automáticamente los valores a partir del Dataset.

num_entradas = np.shape(datos[1])  #shape devuelve las dimensiones de un array, datos es un array bidimensional por lo que el 
num_datos = np.shape(datos[0])      #primer valor de la tupla que devuelve son las filas y el segundo las columnas

# Calcula el vecindario inicial. Debe ser la mitad del lado del mapa de Kohonen
vecindario = lado_mapa/2

# Normaliza los datos si fuese necesario dividiendo cada dato por el máximo en la matriz
# Calculamos el valor maximo de la matriz

valor_maximo = 0
for dato in datos:
    for valor in dato:
        if(valor_maximo < valor):
            valor_maximo = valor  
      
if normalizar_datos:
    datos = datos/valor_max    
    print(datos)
    
# Crea una matriz de pesos con valores random entre 0 y 1. Usa la función random.random de la librería NumPy
#matriz_pesos = np.random.random((dimensiones de la matriz de pesos))

[[0.3671875  0.2578125  0.47265625]
 [0.9453125  0.203125   0.01953125]
 [0.87890625 0.90625    0.73828125]
 [0.21484375 0.42578125 0.6640625 ]
 [0.95703125 0.3671875  0.0546875 ]
 [0.77734375 0.13671875 0.44140625]
 [0.375      0.12890625 0.35546875]
 [0.15625    0.5234375  0.51953125]
 [0.3046875  0.04296875 0.09375   ]
 [0.6484375  0.8984375  0.13671875]
 [0.7890625  0.015625   0.1953125 ]
 [0.5        0.109375   0.86328125]
 [0.30859375 0.3984375  0.5859375 ]
 [0.92578125 0.98828125 0.4921875 ]
 [0.3828125  0.7890625  0.765625  ]
 [0.38671875 0.23046875 0.3125    ]
 [0.9140625  0.30859375 0.40625   ]
 [0.234375   0.6640625  0.05078125]
 [0.359375   0.359375   0.58203125]
 [0.4296875  0.72265625 0.53125   ]
 [0.93359375 0.765625   0.0078125 ]
 [0.515625   0.4375     0.6796875 ]
 [0.234375   0.56640625 0.20703125]
 [0.0859375  0.515625   0.6953125 ]
 [0.82421875 0.64453125 0.0859375 ]
 [0.109375   0.9453125  0.515625  ]
 [0.9296875  0.95703125 0.78515625]
 [0.6328125  0.12890625 0.82

#### Funciones para entrenar/clasificar

In [30]:
# Función para encontrar la BMU
"""
   Encuentra la BMU para un patrón de entrada.
   Entradas: (patrón_de_entrada, matriz_de_pesos, número_de_entradas)
   Salidas:  (bmu, bmu_idx) tupla donde
               bmu: vector de pesos de la neurona ganadora
               bum_idx: coordenadas de la neurona ganadora
"""
def calcular_bmu(patron_entrada, m_pesos, m):

SyntaxError: incomplete input (3651684424.py, line 9)

In [ ]:
# Función para calcular el descenso del coeficiente de aprendizaje (eta)
"""
   Calcula el Learning Rate (eta) que corresponde a la i-ésima presentación.
   Entradas: (learning_rate_inicial, iteracion, período)
   Salidas:  learning_rate para la iteración i

"""
def variacion_learning_rate(lr_inicial, i, n_iteraciones):

In [ ]:
# Función para calcular el descenso del vecindario (v)
"""
   Calcula el vecindario  (v) que corresponde a la i-ésima presentación.
   Entradas: (vecindario_inicial, iteracion, período)
   Salidas:  lvecindario para la iteración i

"""
def variacion_vecindario(vecindario_inicial, i, n_iteraciones):

In [ ]:
# Función para calcular el descenso del coeficiente de aprendizaje (eta) en función de la distancia a la BMU
"""
   Calcula la amortiguación de eta en función de la distancia en el mapa entre una neurona y la BMU.
   Entradas: (distancia_BMU, vecindario_actual)
   Salidas:  amortiguación para la iteración

"""
def decay(distancia_BMU, vecindario_actual):
    return np.exp(-distancia_BMU / (2* (vecindario_actual**2)))

#### Funciones para dibujar la salida de la red

In [ ]:
# Función para pintar una matriz de valores como colores RGB
def pintar_mapa(matriz_valores):
    fig = plt.figure()
    
    # Establece ejes
    ax = fig.add_subplot(111, aspect='equal')
    ax.set_xlim((0, matriz_pesos.shape[0]+1))
    ax.set_ylim((0, matriz_pesos.shape[1]+1))
    ax.set_title('Self-Organising Map después de %d iteraciones' % periodo)

    # Dibuja los rectángulos de color RGB
    for x in range(1, matriz_valores.shape[0] + 1):
        for y in range(1, matriz_valores.shape[1] + 1):
            ax.add_patch(patches.Rectangle((x-0.5, y-0.5), 1, 1,
                         facecolor=matriz_valores[x-1,y-1,:],
                         edgecolor='none'))
    plt.show()

## SOM Entrenamiento

In [ ]:
# Entrena la red con el dataset de entrenamiento



## SOM Clasificación

In [ ]:
# Clasifica los patrones de entrenamiento con la matriz de pesos recién entrenada



## SOM Prueba

In [ ]:
# Clasifica nuevos patrones

