# Práctica 1 - Self-Organising Maps
## Preparación de entorno
#### Importar librerías de código

In [1]:
%reset
# from __future__ import division

import numpy as np
from matplotlib import pyplot as plt
from matplotlib import patches as patches

%matplotlib inline

Nothing done.


#### Dataset que se va a utilizar para el entrenamiento

In [2]:
# Código para obtener el Dataset que se va a usar en el entrenamiento
valor_min = 0
valor_max = 256     #256 porque el valor máximo es exclusivo, es decir, irá de 0 a 255
valores_color = 100
num_colores = 3
datos = np.random.randint(valor_min, valor_max, (valores_color, num_colores))
print(f"Matriz de 100 colores RGB\n",datos)

Matriz de 100 colores RGB
 [[ 17  72 105]
 [156 132 128]
 [213  55  18]
 [136 204 120]
 [ 61 209 254]
 [ 68 132 133]
 [187  16 204]
 [129 204  52]
 [172 254 240]
 [247  42 229]
 [192  23 205]
 [213 104 134]
 [ 36  51 252]
 [119  61 194]
 [ 35 163 210]
 [ 21 162 206]
 [105  67 184]
 [143 115 123]
 [219  39 243]
 [186 175  64]
 [ 61  36 125]
 [  9 229  92]
 [100 160 110]
 [236 138 142]
 [250 157 233]
 [134 153 156]
 [246   1  96]
 [111  27 127]
 [180 158 206]
 [243 130  84]
 [250 253  53]
 [ 83 235 197]
 [ 55  57 204]
 [106  33 121]
 [153 151  96]
 [187 182   8]
 [ 39 108  26]
 [ 67  35 163]
 [124  19 101]
 [245 216 148]
 [ 65 234 182]
 [ 86  84 190]
 [ 15 170 180]
 [251 218 254]
 [239 210 202]
 [101  63  79]
 [134 146  93]
 [ 50  48 136]
 [ 78 167  28]
 [ 48  64 165]
 [128  86 243]
 [ 11  17 181]
 [ 14 126  61]
 [226 156  84]
 [127 251 178]
 [ 70 120  59]
 [246 138  33]
 [254  58  69]
 [ 22  98 149]
 [134  43 209]
 [247  65 241]
 [ 39  32 101]
 [114  40 165]
 [118 185 117]
 [134 168  67

## SOM Setup
#### Variables definidas por el alumno

In [3]:
# Inicializa tamaño del mapa de Kohonen, número de iteraciones y learning rate
# Inicializa normalizar_datos dependiendo de si tienes que normalizar los datos o no
lado_mapa = 
periodo = 
learning_rate = 
normalizar_datos = 

SyntaxError: invalid syntax (58173627.py, line 3)

#### A partir de este punto solo hay cálculos. No se introducen más valores "a mano"

In [ ]:
# Establece el numero de entradas del mapa y el número de datos que se van a usar para entrenar. 
# Utiliza una función que obtenga automáticamente los valores a partir del Dataset.
num_entradas = 
num_datos = 

# Calcula el vecindario inicial. Debe ser la mitad del lado del mapa de Kohonen
vecindario = 

# Normaliza los datos si fuese necesario dividiendo cada dato por el máximo en la matriz
if normalizar_datos:
    datos =
    
# Crea una matriz de pesos con valores random entre 0 y 1. Usa la función random.random de la librería NumPy
#matriz_pesos = np.random.random((dimensiones de la matriz de pesos))

#### Funciones para entrenar/clasificar

In [ ]:
# Función para encontrar la BMU
"""
   Encuentra la BMU para un patrón de entrada.
   Entradas: (patrón_de_entrada, matriz_de_pesos, número_de_entradas)
   Salidas:  (bmu, bmu_idx) tupla donde
               bmu: vector de pesos de la neurona ganadora
               bum_idx: coordenadas de la neurona ganadora
"""
def calcular_bmu(patron_entrada, m_pesos, m):

In [ ]:
# Función para calcular el descenso del coeficiente de aprendizaje (eta)
"""
   Calcula el Learning Rate (eta) que corresponde a la i-ésima presentación.
   Entradas: (learning_rate_inicial, iteracion, período)
   Salidas:  learning_rate para la iteración i

"""
def variacion_learning_rate(lr_inicial, i, n_iteraciones):

In [ ]:
# Función para calcular el descenso del vecindario (v)
"""
   Calcula el vecindario  (v) que corresponde a la i-ésima presentación.
   Entradas: (vecindario_inicial, iteracion, período)
   Salidas:  lvecindario para la iteración i

"""
def variacion_vecindario(vecindario_inicial, i, n_iteraciones):

In [ ]:
# Función para calcular el descenso del coeficiente de aprendizaje (eta) en función de la distancia a la BMU
"""
   Calcula la amortiguación de eta en función de la distancia en el mapa entre una neurona y la BMU.
   Entradas: (distancia_BMU, vecindario_actual)
   Salidas:  amortiguación para la iteración

"""
def decay(distancia_BMU, vecindario_actual):
    return np.exp(-distancia_BMU / (2* (vecindario_actual**2)))

#### Funciones para dibujar la salida de la red

In [ ]:
# Función para pintar una matriz de valores como colores RGB
def pintar_mapa(matriz_valores):
    fig = plt.figure()
    
    # Establece ejes
    ax = fig.add_subplot(111, aspect='equal')
    ax.set_xlim((0, matriz_pesos.shape[0]+1))
    ax.set_ylim((0, matriz_pesos.shape[1]+1))
    ax.set_title('Self-Organising Map después de %d iteraciones' % periodo)

    # Dibuja los rectángulos de color RGB
    for x in range(1, matriz_valores.shape[0] + 1):
        for y in range(1, matriz_valores.shape[1] + 1):
            ax.add_patch(patches.Rectangle((x-0.5, y-0.5), 1, 1,
                         facecolor=matriz_valores[x-1,y-1,:],
                         edgecolor='none'))
    plt.show()

## SOM Entrenamiento

In [ ]:
# Entrena la red con el dataset de entrenamiento



## SOM Clasificación

In [ ]:
# Clasifica los patrones de entrenamiento con la matriz de pesos recién entrenada



## SOM Prueba

In [ ]:
# Clasifica nuevos patrones

